### ISSUE TITLE
shop is getting undefined when redirecting to /api/auth?shop=undefined 

### ISSUE THREAD

**Issue by yashsony** [Shopify/shopify-app-js#94]
# Issue summary
when session verification fails then it redirects to `/api/auth` and passes shop in query parameters but here shop is undefined 
`/api/auth?shop=undefined `

it doesn't happen on development server but it happens on prod server 
followed official [doc](https://shopify.dev/apps/deployment/web) for fly.io deployment but this error exist 

- `@shopify/shopify-app-*` package and version:
- Node version: v18.12.1
- Operating system: don't know (fly.io server)

## Expected behavior

it should redirect to /api/auth?shop=mystore.myshopify.com

## Actual behavior
/api/auth?shop=undefined

## Steps to reproduce the problem

1. clone this repo https://github.com/yashsony/deploymenttesting
2. and deploy it on fly.io through cli  [link](https://shopify.dev/apps/deployment/web)

**Comment by yashsony** [comment]
yes older version v1.0.1 works fine @alexissel

**Comment by TudorBNG** [comment]
Hi. I'm having the same issue as @alexissel:
```
2023-01-25 15:01:20 | backend    | [shopify-app/INFO] Running validateAuthenticatedSession
2023-01-25 15:01:20 | backend    | [shopify-app/INFO] Running validateAuthenticatedSession
2023-01-25 15:01:20 | backend    | [shopify-app/INFO] Session was not valid. Redirecting to /api/auth?shop=undefined | {shop: undefined}
2023-01-25 15:01:20 | backend    | [shopify-app/INFO] Session was not valid. Redirecting to /api/auth?shop=undefined | {shop: undefined}
2023-01-25 15:01:20 | backend    | [shopify-app/ERROR] No shop provided to redirect to auth
```
Node version: 16.18.1

Packages:

- @shopify/app: 3.30.1
- @shopify/cli: 3.30.1
- @shopify/shopify-app-express: 1.1.0

It's great that it works on v1.0.1, but I believe that there are some other gaps there, which have been covered in v1.1.0. So it would be great to have a fix for this redirect after uninstall issue in v1.1.1 as it is a requirement in the current app approval process 😄

**Comment by JeaneC** [comment]
+1 started to see this as well

```
2023-01-29T06:18:34.841 app[8814583e] mia [info] [shopify-app/INFO] Running ensureInstalledOnShop

2023-01-29T06:18:34.897 app[8814583e] mia [info] [shopify-app/INFO] Running ensureInstalledOnShop

2023-01-29T06:18:34.899 app[8814583e] mia [info] [shopify-app/INFO] App is installed and ready to load | {shop: 126teststorejc.myshopify.com}

2023-01-29T06:18:35.212 app[8814583e] mia [info] [shopify-api/INFO] Beginning OAuth | {shop: 126teststorejc.myshopify.com, isOnline: false, callbackPath: /api/auth/callback}

2023-01-29T06:18:35.356 app[8814583e] mia [info] [shopify-app/INFO] Running validateAuthenticatedSession

2023-01-29T06:18:35.358 app[8814583e] mia [info] [shopify-app/INFO] Session was not valid. Redirecting to /api/auth?shop=undefined | {shop: undefined}
```

**Comment by granteagon** [comment]
I put the above solution in place and it worked, but this was working before.  I'm not sure why it suddenly doesn't work.  I didn't upgrade my packages and it went from a working status to a non-working status.

**Comment by walkingbrad** [comment]
+1 same issue

I've noticed the issue in both dev (using sqlite session storage) and in prod (using redis session storage). I haven't uninstalled my app on the stores that have issue, so my issue can't be related to that. But the issue does seem to occur when I simply wipe the sessions from session storage (e.g. delete my `database.sqlite` file in dev or clear all entries from Redis).

By referencing the logs that Shopify spits out, the issue does seem to occur somewhere in `validateAuthenticatedSession`. Since some say this wasn't an issue in `1.0.1`, I took a look at the [old implementation of that method](https://github.com/Shopify/shopify-app-js/blob/%40shopify/shopify-app-express%401.0.1/packages/shopify-app-express/src/middlewares/validate-authenticated-session.ts). If we compare that to the latest code in `1.1.0`, we see that the old code has an additional branch in which it can determine the value of the `shop` parameter. Presumably, reintroducing this logic would solve the issue:
```
else if (api.config.isEmbeddedApp) {
  const payload = await api.session.decodeSessionToken(token);
  shop = payload.dest.replace('https://', '');
}
```

**Comment by alexissel** [comment]
This is still not fixed in `v1.2.0`!

**Comment by mkevinosullivan** [comment]
Fixed in `@shopify/shopify-app-express@1.2.1`

**Comment by alexissel** [comment]
Thanks Kevin!

**Comment by olafghanizadeh** [comment]
This issue still persists in @shopify/shopify-app-express@1.2.2

**Comment by AleksandrBy** [comment]
Yes. In @shopify/shopify-app-express@2.0.0 too
